#!/bin/bash

##This takes the integer and provides the system info

echo -e "Choose from the options [1-3]\n1) CPU \n2) RAM\n3) Storage" 

read -p "Selection: " choice
echo
case $choice in
    1)
        echo "Heres the CPU usage"
        uptime
        ;;   
    2)
        echo "Here is the RAM usage"
        free -h
        ;;
    3)
        echo "Here is the Storage Usage"
        df -h
        ;;
    *)
        echo "We dont have that option"
        ;;
esac






